# Generated by Django 3.1.7 on 2021-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=60, verbose_name='Shorted link')),
                ('actual', models.CharField(max_length=200, verbose_name='Actual url')),
            ],
        ),
    ]
